import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
import { ExternalLink, Eye, MoreVertical, Star } from 'lucide-react';
import { Timer } from './Timer';
import { TaskContextMenu } from './TaskContextMenu';
export const TaskTable = ({ tasks, onRefresh, onViewDrawing }) => {
    const [openMenuId, setOpenMenuId] = useState(null);
    const getStatusColor = (status) => {
        switch (status) {
            case 'Đang làm': return 'bg-blue-100 text-blue-700 border-blue-200';
            case 'Chờ duyệt': return 'bg-amber-100 text-amber-700 border-amber-200';
            case 'Hoàn thành': return 'bg-emerald-100 text-emerald-700 border-emerald-200';
            default: return 'bg-slate-100 text-slate-700 border-slate-200';
        }
    };
    const getProductivityColor = (target, actual) => {
        if (actual === 0)
            return 'text-slate-400';
        const ratio = (target / actual) * 100;
        if (ratio < 80)
            return 'text-rose-600 font-bold';
        if (ratio > 100)
            return 'text-emerald-600 font-bold';
        return 'text-slate-700';
    };
    return (_jsx("div", { className: "bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-slate-50 border-bottom border-slate-200", children: [_jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider", children: "T\u00EAn b\u1EA3n v\u1EBD" }), _jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider", children: "K\u1EF9 s\u01B0" }), _jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider", children: "\u0110\u1ED9 kh\u00F3" }), _jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider", children: "Tr\u1EA1ng th\u00E1i" }), _jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider", children: "H\u1EA1n ch\u00F3t" }), _jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider", children: "N\u0103ng su\u1EA5t (T/A)" }), _jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider", children: "Theo d\u00F5i gi\u1EDD" }), _jsx("th", { className: "px-6 py-4 text-xs font-semibold text-slate-500 uppercase tracking-wider text-right", children: "Thao t\u00E1c" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-100", children: tasks.map((task) => (_jsxs("tr", { className: "hover:bg-slate-50/50 transition-colors group", children: [_jsx("td", { className: "px-6 py-4", children: _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "font-medium text-slate-900", children: task.drawing_name }), _jsxs("span", { className: "text-xs text-slate-500", children: ["D\u1EF1 \u00E1n ID: ", task.project_id.slice(0, 8), "..."] })] }) }), _jsx("td", { className: "px-6 py-4 text-sm text-slate-600", children: task.engineer_name }), _jsx("td", { className: "px-6 py-4", children: _jsx("div", { className: "flex gap-0.5", children: [...Array(5)].map((_, i) => (_jsx(Star, { size: 14, className: i < task.difficulty ? "text-amber-400 fill-amber-400" : "text-slate-200" }, i))) }) }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `px-2.5 py-1 rounded-full text-xs font-medium border ${getStatusColor(task.status)}`, children: task.status }) }), _jsx("td", { className: "px-6 py-4", children: task.deadline ? (_jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: `text-sm font-medium ${new Date(task.deadline) < new Date() && task.status !== 'Hoàn thành'
                                                    ? 'text-rose-600'
                                                    : 'text-slate-700'}`, children: new Date(task.deadline).toLocaleDateString('vi-VN') }), new Date(task.deadline) < new Date() && task.status !== 'Hoàn thành' && (_jsx("span", { className: "text-[10px] text-rose-500 font-bold uppercase", children: "Qu\u00E1 h\u1EA1n" }))] })) : (_jsx("span", { className: "text-slate-400 text-xs italic", children: "Ch\u01B0a \u0111\u1EB7t" })) }), _jsx("td", { className: "px-6 py-4", children: _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: `text-sm ${getProductivityColor(task.target_hours, task.actual_hours)}`, children: task.actual_hours > 0 ? `${((task.target_hours / task.actual_hours) * 100).toFixed(1)}%` : '-%' }), _jsxs("span", { className: "text-[10px] text-slate-400", children: [task.target_hours, "h / ", task.actual_hours.toFixed(1), "h"] })] }) }), _jsx("td", { className: "px-6 py-4", children: _jsx(Timer, { taskId: task.id, onTimeUpdate: onRefresh, isRunning: task.status === 'Đang làm' }) }), _jsx("td", { className: "px-6 py-4 text-right", children: _jsxs("div", { className: "flex items-center justify-end gap-2 relative", children: [task.viewer_link && (_jsx("button", { onClick: () => onViewDrawing(task.viewer_link), className: "p-2 text-slate-400 hover:text-emerald-500 hover:bg-emerald-50 rounded-lg transition-colors", title: "Xem b\u1EA3n v\u1EBD", children: _jsx(Eye, { size: 18 }) })), task.drive_link && (_jsx("a", { href: task.drive_link, target: "_blank", rel: "noopener noreferrer", className: "p-2 text-slate-400 hover:text-blue-500 hover:bg-blue-50 rounded-lg transition-colors", title: "M\u1EDF Drive", children: _jsx(ExternalLink, { size: 18 }) })), _jsx("button", { onClick: () => setOpenMenuId(openMenuId === task.id ? null : task.id), className: "p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors", children: _jsx(MoreVertical, { size: 18 }) }), openMenuId === task.id && (_jsx(TaskContextMenu, { task: task, onClose: () => setOpenMenuId(null), onRefresh: onRefresh }))] }) })] }, task.id))) })] }) }) }));
};
